[package]
name = "sw4-account-creator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
actix-files = "0.6.0"
clap = { version = "4.4.18", features = ["derive"] }
tera = "1.19.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
